#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("TheSolarBlinds.Resource", IsApplication=true)]

namespace TheSolarBlinds
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int blinds_down_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int blinds_stop_icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int blinds_up_icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int condition_01d = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int condition_01n = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int condition_02d = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int condition_02n = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int condition_03d = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int condition_03n = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int condition_04d = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int condition_04n = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int condition_09d = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int condition_09n = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int condition_10d = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int condition_10n = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int condition_11d = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int condition_11n = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int condition_13d = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int condition_13n = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int condition_50d = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int condition_50n = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Icon = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int menu_battery_icon = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int menu_motor_icon = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int menu_sync_icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int menu_weather_icon = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int blinds_down_btn = 2131034124;
			
			// aapt resource value: 0x7f05000d
			public const int blinds_stop_btn = 2131034125;
			
			// aapt resource value: 0x7f05000b
			public const int blinds_up_btn = 2131034123;
			
			// aapt resource value: 0x7f05002d
			public const int currentWeatherSection = 2131034157;
			
			// aapt resource value: 0x7f050032
			public const int forecastSection = 2131034162;
			
			// aapt resource value: 0x7f050007
			public const int forecast_condition_text = 2131034119;
			
			// aapt resource value: 0x7f050006
			public const int forecast_image = 2131034118;
			
			// aapt resource value: 0x7f050002
			public const int forecast_list_view = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int forecast_temperature_text = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int forecast_time_text = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int forecaste_date_text = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int getForecastButton = 2131034113;
			
			// aapt resource value: 0x7f05002b
			public const int getSection = 2131034155;
			
			// aapt resource value: 0x7f050000
			public const int linearLayout1 = 2131034112;
			
			// aapt resource value: 0x7f05000e
			public const int linearLayout2 = 2131034126;
			
			// aapt resource value: 0x7f05001b
			public const int linearLayout3 = 2131034139;
			
			// aapt resource value: 0x7f05001f
			public const int linearLayout4 = 2131034143;
			
			// aapt resource value: 0x7f050008
			public const int menu_motor_btn = 2131034120;
			
			// aapt resource value: 0x7f05000a
			public const int menu_sync_btn = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int menu_weather_btn = 2131034121;
			
			// aapt resource value: 0x7f050035
			public const int roomTempLabel = 2131034165;
			
			// aapt resource value: 0x7f050034
			public const int roomTempSection = 2131034164;
			
			// aapt resource value: 0x7f050036
			public const int roomTempText = 2131034166;
			
			// aapt resource value: 0x7f05000f
			public const int sync_btn = 2131034127;
			
			// aapt resource value: 0x7f05001c
			public const int sync_delete_btn = 2131034140;
			
			// aapt resource value: 0x7f050027
			public const int sync_device_id = 2131034151;
			
			// aapt resource value: 0x7f050024
			public const int sync_id = 2131034148;
			
			// aapt resource value: 0x7f050023
			public const int sync_list_view = 2131034147;
			
			// aapt resource value: 0x7f050025
			public const int sync_nickname = 2131034149;
			
			// aapt resource value: 0x7f050010
			public const int sync_read_write_btn = 2131034128;
			
			// aapt resource value: 0x7f05001e
			public const int sync_save_btn = 2131034142;
			
			// aapt resource value: 0x7f05001d
			public const int sync_set_btn = 2131034141;
			
			// aapt resource value: 0x7f05001a
			public const int sync_set_device_id = 2131034138;
			
			// aapt resource value: 0x7f050014
			public const int sync_set_id = 2131034132;
			
			// aapt resource value: 0x7f050021
			public const int sync_set_message = 2131034145;
			
			// aapt resource value: 0x7f050017
			public const int sync_set_nickname = 2131034135;
			
			// aapt resource value: 0x7f050011
			public const int tableLayout1 = 2131034129;
			
			// aapt resource value: 0x7f050012
			public const int tableRow1 = 2131034130;
			
			// aapt resource value: 0x7f050015
			public const int tableRow2 = 2131034133;
			
			// aapt resource value: 0x7f050018
			public const int tableRow3 = 2131034136;
			
			// aapt resource value: 0x7f050022
			public const int textView1 = 2131034146;
			
			// aapt resource value: 0x7f050016
			public const int textView13 = 2131034134;
			
			// aapt resource value: 0x7f050019
			public const int textView17 = 2131034137;
			
			// aapt resource value: 0x7f050013
			public const int textView18 = 2131034131;
			
			// aapt resource value: 0x7f050020
			public const int textView19 = 2131034144;
			
			// aapt resource value: 0x7f050026
			public const int textView2 = 2131034150;
			
			// aapt resource value: 0x7f050028
			public const int weatherSection = 2131034152;
			
			// aapt resource value: 0x7f05002e
			public const int weather_current_city_text = 2131034158;
			
			// aapt resource value: 0x7f050030
			public const int weather_current_condition_text = 2131034160;
			
			// aapt resource value: 0x7f050031
			public const int weather_current_temperature_text = 2131034161;
			
			// aapt resource value: 0x7f05002f
			public const int weather_current_weather_image = 2131034159;
			
			// aapt resource value: 0x7f050033
			public const int weather_forecast_btn = 2131034163;
			
			// aapt resource value: 0x7f05002c
			public const int weather_get_update_btn = 2131034156;
			
			// aapt resource value: 0x7f05002a
			public const int weather_zipcode_text = 2131034154;
			
			// aapt resource value: 0x7f050029
			public const int zipCodeSection = 2131034153;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ForecastLayout = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ForecastListView = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MotorLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int SyncLayout = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int SyncListView = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int WeatherLayout = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
